#!/usr/bin/env python

import os

from ConfigParser import ConfigParser

from bartclock.bart_lib import departure_info_for_station

config = ConfigParser()
config.read('./config.ini')

info = departure_info_for_station(url=config.get('bart', 'base_url'),
                                  key=os.environ.get('BART_API_KEY'),
                                  station=config.get('bart', 'origin'))

print info